### ISSUE TITLE
Cli creates wrong "app" path when config.xml has <content> entry on windows

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js-cli#6]
when the config.xml file already has a <content> entry like `<content src="src/package.json" />` the build produces a path in the altered build config.xml with backslashes on windows. This does not work mobile devices: `<content src="app\src\package.json" />`.

**Comment by ralfstx** [comment]
On Windows, the Node.js `path.join` method uses backslashes as path separator. However, backslashes are not supported in the `config.xml`. Consequently, the CLI must NOT use `path.join` to compute paths that end up in this file.

Since Windows also supports forward slashes, it might be generally a better idea to use a custom join method that *always* uses slashes. I'd however still prefer a `join()` method over manual path concatenation.
